def menu_kubelet():
    print()
    print("1 - List Pods;")
    print("2 - List Secrets;")
    print("3 - Shell in Pod;")
    print("4 - Deploy Busybox Pod;")
    print("5 - Delete Pod;")
    print("6 - Get Host Access;")
    print("menu - Show the Menu;")
    print("exit - Close K8skiller;")
    print()

def menu_api():
    print()
    print("1 - List Secrets;")
    print("2 - List Pods;")
    print("3 - Shell in Pod;")
    print("4 - Deploy Busybox Pod;")
    print("5 - Delete Pod;")
    print("menu - Show the Menu;")
    print("exit - Close K8skiller;")
    print()
def menu_service():
    print()
    print("1 - List Pods;")
    print("2 - Shell in Pod;")
    print("3 - Deploy Busybox Pod;")
    print("4 - Delete Pod;")
    print("menu - Show the Menu;")
    print("exit - Close K8skiller;")
    print()